name: Flutter Web

on:
  push:
    branches: 
        - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: cd build/web
      - run: git init 
      - run: git config --global user.email hackmonker127001@protonmail.com
      - run: git config --global user.name hackmonker
      - run: git status
      - run: git remote add origin https://${{secrets.commit_secret}}@github.com/hackmonker/portfolio.git
      - run: git checkout -b gh-pages
      - run: git add --all
      - run: git commit -m "update"
      - run: git push origin gh-pages -f
